#!/usr/bin/env node
///////////////////////////////////////////////////////////////////////////////////
// The MIT License (MIT)
//
// Copyright (c) 2019 Tarek Sherif
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
///////////////////////////////////////////////////////////////////////////////////

"use strict";

const puppeteer = require("puppeteer");
const pti = require("puppeteer-to-istanbul");
const http = require("http");
const fs = require("fs").promises;
const path = require("path");
const glob = require("glob").sync;
const copydir = require("copy-dir").sync;
const rimraf = require("rimraf").sync;
const PNG = require("pngjs").PNG;
const pixelmatch = require("pixelmatch");

//////////////////
// CONFIGURATION
//////////////////


const GLTEST_PKG = require(path.resolve(__dirname, "package.json"));
const HELP_MESSAGE = `usage: glcheck [--help] [--version] [--config PATH] [--unit-test-dir PATH]
                        [--asset-dir PATH] [--reference-image-dir PATH] [--render-test-threshold VAL]
                        [--render-timeout TIME] [--save-render-failures {true/false}]
                        [--render-failure-dir PATH] [--server-port PORT] [--coverage {true/false}] 
                        [--headless {true/false}] [--only PATH]

Test WebGL 1 and 2 applications.

Optional arguments:
  --help                              Show this help message and exit.
  --version                           Show program's version number and exit.
  --config PATH                       Path to config file (default: ./glcheck.config.json)
  --unit-test-dir PATH                Path to output unit test results to [default: glcheck-tests/unit-tests/].
  --asset-dir PATH                    Directory to copy assets from for unit tests.
  --reference-image-dir PATH          Path to render test reference images [default: glcheck-tests/reference-images/].
  --render-test-threshold VAL         Match threshold between 0 and 1 for render tests [default: 0.99].
  --render-timeout TIME               Timeout for each render test in milliseconds [default: 5000].
  --save-render-failures {true/false} Save render failures and diffs [default: false].
  --render-failure-dir PATH           Path to save render failures and diffs to [default: glcheck-tests/render-failures/].
  --server-port PORT                  Port to run testing server on [default: 7171].
  --headless {true/false}             Run headless [default: true].
  --coverage {true/false}             Generate coverage results that can be consumed by Istanbul [default: false].
  --only PATH                         Only run test file PATH (can be a glob pattern to run multiple files).
`;

let config = {
    unitTestDir: "glcheck-tests/unit-tests/",
    serverPort: 7171,
    unitTests: [],
    renderTests: [],
    referenceImageDir: "glcheck-tests/reference-images/",
    renderTestThreshold: 0.99,
    renderTimeout: 5000,
    saveRenderFailures: false,
    renderFailureDir: "glcheck-tests/render-failures/",
    assetDir: null,
    coverage: false,
    coverageExcludeFiles: [],
    headless: true,
    only: null
};

const argv = process.argv.slice(2);
const argc = argv.length;
const args = {};

for (let i = 0; i < argc; ++i) {
    let [ flag, arg ] = argv[i].split("=");

    switch(flag) {
        case "--config":
            args.configPath = arg || argv[++i];
            break;
        case "--coverage":
            arg = arg || argv[++i];
            args.coverage = arg.toLowerCase() !== "false";
            break;
        case "--headless":
            arg = arg || argv[++i];
            args.headless = arg.toLowerCase() !== "false";
            break;
        case "--server-port":
            args.serverPort = parseInt(arg || argv[++i], 10);
            break;
        case "--unit-test-dir":
            args.unitTestDir = arg || argv[++i];
            break;
        case "--asset-dir":
            args.assetDir = arg || argv[++i];
            break;
        case "--reference-image-dir":
            args.referenceImageDir = arg || argv[++i];
            break;
        case "--render-test-threshold":
            args.renderTestThreshold = parseFloat(arg || argv[++i]);
            break;
        case "--render-timeout":
            args.renderTimeout = parseInt(arg || argv[++i], 10);
            break;
        case "--save-render-failures":
            arg = arg || argv[++i];
            args.saveRenderFailures = arg.toLowerCase() !== "false";
            break;
        case "--render-failure-dir":
            args.renderFailureDir = arg || argv[++i];
            break;
        case "--only":
            args.only = arg || argv[++i];
            break;
        case "--self-test":
            args.selfTest = true;
            break;
        case "--clear-config":
            args.clearConfig = true;
            break;
        case "--version":
            console.log(GLTEST_PKG.version);
            process.exit(0);
            break;
        case "--help":
            console.log(HELP_MESSAGE);
            process.exit(0);
            break;
        default: 
            console.log(`\u001b[31mgltest unknown argument: ${flag}\u001b[0m`);
            process.exit(1);
    }
}

const configPath = path.resolve(".", args.configPath || "glcheck.config.json");

try {
    Object.assign(config, require(configPath));
    config.unitTests = config.unitTests || [];
    config.renderTests = config.renderTests || [];
    config.coverageExcludeFiles = config.coverageExcludeFiles || [];
    if (!Array.isArray(config.unitTests)) {
        config.unitTests = [ config.unitTests ];
    }
    if (!Array.isArray(config.renderTests)) {
        config.renderTests = [ config.renderTests ];
    }
    if (!Array.isArray(config.coverageExcludeFiles)) {
        config.coverageExcludeFiles = [ config.coverageExcludeFiles ];
    }
} catch (e) {
    if (args.configPath) {
        console.log(`\u001b[31mError: Config file '${args.configPath}' not found.\u001b[0m\n`);
        process.exit(1);
    }
}

if (args.clearConfig) {
    config = { 
        unitTests: config.unitTests,
        renderTests: config.renderTests,
        coverageExcludeFiles: config.coverageExcludeFiles
    };
}

Object.assign(config, args);


const SELF_TEST = Boolean(args.selfTest);
const UNIT_TEST_DIR = path.resolve(".", config.unitTestDir);
const ASSET_DIR = path.resolve(UNIT_TEST_DIR, "assets");
const COVERAGE_DIR = path.resolve(".", ".nyc_output");
const REFERENCE_IMAGE_DIR = path.resolve(".", config.referenceImageDir);
const RENDER_FAILURE_DIR = path.resolve(".", config.renderFailureDir);
const BASE_URL = `http://localhost:${config.serverPort}/`;
const RENDER_POLLING = 10;

///////////////
// FILE PATHS
///////////////

let unitTests = [];
let renderTests = [];

config.unitTests.forEach(t => {
    unitTests.push(...glob(t));
});

config.renderTests.forEach((t) => {
    renderTests.push(...glob(t));
});

if (config.only) {
    const only = {};

    glob(config.only).forEach(p => only[p] = true);

    unitTests = unitTests.filter(t => only[t]);
    renderTests = renderTests.filter(t => only[t]);
}

const EXCLUDE_FILES = [];
const EXCLUDE_REGEX = [];

config.coverageExcludeFiles.forEach((t) => {
    EXCLUDE_FILES.push(...glob(t));
});

unitTests.concat(EXCLUDE_FILES).forEach(p => {
    EXCLUDE_REGEX.push(new RegExp(`/${p}$`));
});


/////////////////
// LOCAL SERVER
/////////////////

const MIME_TYPES = {
    ".css": "text/css",
    ".html": "text/html",
    ".js": "text/javascript",
    ".json": "application/json",
    ".txt": "text/plain",
    ".jpeg": "image/jpeg",
    ".jpg": "image/jpeg",
    ".png": "image/png",
    ".gif": "image/gif",
    ".bmp": "image/bmp",
    ".mov": "video/quicktime",
    ".mpeg": "video/mpeg",
    ".mpg": "video/mpeg",
    ".ogv": "video/ogg"
};

const server = http.createServer((req, res) => {
    const url = req.url; 
    const requestPath = decodeURI(url.replace(/^\/+/, "").replace(/\?.*$/, ""));
    const filePath = path.resolve(".", requestPath);
    const mimeType = MIME_TYPES[path.extname(filePath)] || "application/octet-stream";

    fs.readFile(filePath).then(content => {
        res.setHeader("Content-Type", mimeType);
        res.end(content);
    });
}).listen(config.serverPort);

(async () => {

    //////////////
    // RUN TESTS
    //////////////

    // Report results per test
    let results = {
        passed: true,
        numTests: 0,
        numAssertions: 0,
        numFailed: 0
    };

    /////////////////////
    // LAUNCH PUPPETEER
    /////////////////////


    const browser = await puppeteer.launch({headless: config.headless});
    const page = await browser.newPage();

    /////////////////////////////////////
    // PAGE ERROR HANDLERS AND COVERAGE
    /////////////////////////////////////

    // Report errors from the page
    page.on("console", msg => {
        if (msg.type() === "error") {
            console.log(`\u001b[31m${msg.text()}\u001b[0m\n`);
        }
    });

    page.on("pageerror", error => {
        console.log(`\u001b[31m${error.message}\u001b[0m\n`);

        server.close();
        browser.close();

        process.exit(1);
    });


    if (config.coverage) {
        rimraf(COVERAGE_DIR);
        await page.coverage.startJSCoverage({
            resetOnNavigation: false
        });
    }

    if (unitTests.length > 0) {
        ///////////////////////////////
        // SET UP UNIT TEST DIRECTORY
        ///////////////////////////////

        rimraf(UNIT_TEST_DIR);

        const [ template, qunit, glcheck ] = await Promise.all([
            fs.readFile(path.resolve(__dirname, "page/index-template.html"), "utf8"),
            fs.readFile(path.resolve(__dirname, "page/qunit-2.9.2.js"), "utf8"),
            fs.readFile(path.resolve(__dirname, "page/glcheck.js"), "utf8"),
            fs.mkdir(UNIT_TEST_DIR, {recursive: true})
        ]);

        const testPaths = [];
        unitTests.forEach(p => {
            testPaths.push(`import "/${p}";`);
        });

        let index = template
        .replace("QUNIT_IMPORT", qunit)
        .replace("GLTEST_IMPORT", SELF_TEST ? "<script src=\"./glcheck.js\"></script>" : `<script>${glcheck}</script>`)
        .replace("FRAMEWORK_IMPORTS", testPaths.join("\n"));

        const writes = [ fs.writeFile(path.resolve(UNIT_TEST_DIR, "index.html"), index) ];

        if (config.assetDir) {
            writes.push(fs.mkdir(ASSET_DIR).then(() => copydir(path.resolve(".", config.assetDir), ASSET_DIR)));
        }

        if (SELF_TEST) {
            // Include glcheck.js as external script so it shows up in coverage reports
            writes.push(fs.writeFile(path.resolve(UNIT_TEST_DIR, "glcheck.js"), glcheck));
        }

        await Promise.all(writes);

        await new Promise((resolve) => {
            ///////////////////
            // RUN UNIT TESTS
            ///////////////////

            const testEndPromise = page.exposeFunction("glcheck_testEnd", (test) => {
                const assertions = test.assertions;
                const count = assertions.length;
                if (count === 0) {
                    return;
                }
                results.numTests++;
                results.numAssertions += count;
                if (test.status === "passed") {
                    console.log(`\u001b[32m\u2714\u001b[0m ${test.name}`);
                } else {
                    for (let j = 0; j < count; ++j) {
                        const assertion = assertions[j];
                        if (!assertion.passed) {
                            console.log(`\n\u001b[31m\u274c\u001b[0m ${test.name}: ${assertion.message}`);
                            console.log(`    ${assertion.negative ? "Did not expect:" : "Expected: "}\u001b[32m ${JSON.stringify(assertion.expected)}\u001b[0m`);
                            console.log(`    Got:${" ".repeat(assertion.negative ? 11 : 6)}\u001b[31m ${JSON.stringify(assertion.actual)}\u001b[0m\n`);
                            console.log(assertion.stack);
                            console.log("\n");
                        }
                    }
                }
            });

            // Report final results
            const runEndPromise = page.exposeFunction("glcheck_runEnd", (run) => {
                results.passed = run.status === "passed";
                results.numFailed = run.testCounts.failed;

                resolve();
            });

            return Promise.all([ testEndPromise, runEndPromise ])
            .then(() => page.goto(`${BASE_URL}${config.unitTestDir}/index.html`));
        });
    }

    if (renderTests.length > 0) {
        /////////////////
        // RENDER TESTS
        /////////////////

        /////////////////////////////////
        // SET UP RENDER TEST DIRECTORY
        /////////////////////////////////

        const dirWrites = [fs.mkdir(REFERENCE_IMAGE_DIR, {recursive: true})];

        if (config.saveRenderFailures) {
            dirWrites.push(fs.mkdir(RENDER_FAILURE_DIR, {recursive: true}))
        }

        await Promise.all(dirWrites);
        
        const renderTestURLs = [];
        renderTests.forEach(p => {
            renderTestURLs.push({
                testURL: `${BASE_URL}${p}`,
                testPath: p,
                referenceFileName: `${p.replace(/\//g, "-")}.png`
            });
        });

        /////////////////////
        // RUN RENDER TESTS
        /////////////////////


        const instrumentAnimationFrame = `
            window.glcheck_setRAFCount = function(numFrames) {
                if (!Number.isFinite(numFrames)) {
                    throw new Error("glcheck_animationFrameCount: Argument is not a number.");
                }

                window.GLCHECK_RAF_COUNT = numFrames;

                if (!window.GLCHECK_RAF_INSTRUMENTED) {
                    let currentFrame = 0;
                    const raf = window.requestAnimationFrame;
                    window.requestAnimationFrame = (fn) => {
                        if (currentFrame++ < window.GLCHECK_RAF_COUNT) {
                            return raf(fn);
                        } else {
                            window.glcheck_renderDone = true;
                        }
                    };

                    window.GLCHECK_RAF_INSTRUMENTED = true;
                }
            };
        `;
        
        await page.evaluateOnNewDocument(instrumentAnimationFrame);

        let renderTestPromises = Promise.resolve();
        renderTestURLs.forEach(({testURL, testPath, referenceFileName}) => {
            const referencePath = path.resolve(REFERENCE_IMAGE_DIR, referenceFileName);
            renderTestPromises = renderTestPromises.then(() => {
                return fs.stat(referencePath)
                .then(() => {
                    results.numAssertions++;
                    results.numTests++;

                    return page.goto(testURL)
                    .then(() => page.waitForFunction("window.glcheck_renderDone", {polling: RENDER_POLLING, timeout: config.renderTimeout}))
                    .then(() => Promise.all([ page.screenshot(), fs.readFile(referencePath) ]))
                    .then(([ actualData, expectedData ]) => {
                        const actual = PNG.sync.read(actualData);
                        const expected = PNG.sync.read(expectedData);
                        const {width, height} = actual;
                        const numPixels = width * height;

                        let diffImage = null;
                        let diffData = null;

                        if (config.saveRenderFailures) {
                            diffImage = new PNG({width, height});
                            diffData = diffImage.data;
                        }

                        const diff = pixelmatch(actual.data, expected.data, diffData, width, height);
                        const match = 1.0 - diff / numPixels;

                        const passed = match >= config.renderTestThreshold;

                        if (passed) {
                            console.log(`\u001b[32m\u2714\u001b[0m Render: ${testPath}`);
                            return null;
                        } else {
                            results.passed = false;
                            results.numFailed++;
                            console.log(`\n\u001b[31m\u274c\u001b[0m Render: ${testPath}`);
                            console.log(`    Threshold:  \u001b[32m${config.renderTestThreshold}\u001b[0m`);
                            console.log(`    Match:      \u001b[31m${match.toFixed(3)}\u001b[0m\n`);
                            console.log("\n");

                            if (config.saveRenderFailures) {
                                const failurePath = path.resolve(RENDER_FAILURE_DIR, referenceFileName.replace(/\.png$/, "-failure.png"));
                                const diffPath = path.resolve(RENDER_FAILURE_DIR, referenceFileName.replace(/\.png$/, "-diff.png"));

                                return Promise.all([
                                    fs.writeFile(failurePath, PNG.sync.write(actual)),
                                    fs.writeFile(diffPath, PNG.sync.write(diffImage))
                                ]);
                            }
                        }
                    }).catch(e => {
                        results.passed = false;
                        results.numFailed++;
                        console.log(`\n\u001b[31m\u274c\u001b[0m Render: ${testPath}\n`);
                        if (e.name === "TimeoutError") {
                            console.log("\u001b[31mError: Render test timeout (did you forget to set 'glcheck_renderDone' in the page?)\u001b[0m\n");
                        } else {
                            console.log(`\u001b[31m${e.stack}\u001b[0m\n`);
                        }
                    });
                }).catch(() => {
                    console.log(`\n\u001b[33mCapturing reference image: ${testPath}\u001b[0m`);
                    
                    return page.goto(testURL)
                    .then(() => page.waitForFunction("window.glcheck_renderDone", {polling: RENDER_POLLING, timeout: config.renderTimeout}))
                    .then(() => page.screenshot({ path: referencePath }))
                    .catch((e) => {
                        console.log(`\n\u001b[31mError while capturing reference image: ${testPath}\u001b[0m`);
                        if (e.name === "TimeoutError") {
                            console.log("\u001b[31mRender test timeout (did you forget to set 'glcheck_renderDone' in the page?)\u001b[0m\n");
                        } else {
                            console.log(`\u001b[31m${e.stack}\u001b[0m\n`);
                        }
                    });
                }); 
            });
        });

        await renderTestPromises;
    }

    if (config.coverage) {

        ////////////////////
        // COVERAGE REPORT
        ////////////////////

        await page.coverage.stopJSCoverage().then((jsCoverage) => {
            jsCoverage = jsCoverage.filter(item => {
                const url = item.url;

                // Filter out scripts embedded in index.html
                // (i.e. test runner scripts)
                if (url.match(/\.html$/)) {
                    return false;
                }

                // Filter out test files and files
                // excluded by config
                let include = true;
                EXCLUDE_REGEX.forEach(ex => {
                    if (url.match(ex)) {
                        include = false;
                    }
                });

                return include; 
            });

            // Puppeteer to Istanbul separates repeat entries
            const consolidatedEntries = {};
            jsCoverage.forEach(item => {
                const url = item.url;

                if (!consolidatedEntries[url]) {
                    consolidatedEntries[url] = item;  
                } else {
                    consolidatedEntries[url].ranges = consolidatedEntries[url].ranges.concat(item.ranges);
                }
            });


            const consolidatedCoverage = [];
            for (const url in consolidatedEntries) {
                consolidatedCoverage.push(consolidatedEntries[url]);
            }

            pti.write(consolidatedCoverage);
        });
    }

    ////////////////////
    // FINAL REPORT
    ////////////////////

    console.log(`\nRan ${results.numTests} tests (${results.numAssertions} assertions)...\n`);

    if (results.passed) {
        console.log("\u001b[32mAll tests passed!\u001b[0m\n");
    } else {
        console.log(`\t\u001b[31m${results.numFailed} tests failed.\u001b[0m\n\n`);
    }

    await Promise.all([
        server.close(),
        browser.close()
    ]);

    process.exit(results.passed ? 0 : 1);
})();

